spring:
  application:
    name: chap07-transaction-lecture-source

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/menudb
    username: swcamp
    password: swcamp

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.jinosoft.transaction
  mapper-locations: mappers/*.xml